module.exports = {
  plugins: ["prettier-plugin-tailwindcss", require.resolve("@trivago/prettier-plugin-sort-imports")],
  trailingComma: "es5",
  tabWidth: 2,
  printWidth: 120,
  semi: false,
  importOrder: [
    "^react$",
    "^next/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/app/(.*)$",
    "^@/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderGroupNamespaceSpecifiers: true,
  importOrderCaseInsensitive: true,
}
